function bicycle_tf= get_bicycle_fb_tf(h, V, a, b, k1, k2, c, lambda)
    g = 9.81; % graviational accelration
    bicycle_tf = tf( ...
        [a*V*sin(lambda)/(b*h)*k1, (V^2*h-a*c*g)*sin(lambda)/(b*h^2)*k1], ...
        [1, a*V*sin(lambda)/(b*h)*k2, (-g/h + k2*(V^2*h-a*c*g)*sin(lambda)/(b*h^2))] ...
    );
end